### ISSUE TITLE
remote debug address is incorrect

### ISSUE THREAD

**Issue by yifeikong** [joelgriffith/browserless#169]
<img width="432" alt="image" src="https://user-images.githubusercontent.com/1035487/57667221-58ff9580-7635-11e9-9fed-d92203625c82.png">

I have set HOST as 10.40.10.40. when I click on current sessions on localhost, I got incorrent address:

http://10.40.10.40:3000/devtools/inspector.html?ws=127.0.0.1:3000/devtools/page/690FA73CD296B978D0A2E2B8DEAD2FE9

which should be:

http://10.40.10.40:3000/devtools/inspector.html?ws=10.40.10.40:3000/devtools/page/690FA73CD296B978D0A2E2B8DEAD2FE9

**Comment by joelgriffith** [comment]
Good fine, I'll have a PR up shortly that'll fix this.

**Comment by joelgriffith** [comment]
Fixed in https://github.com/joelgriffith/browserless/pull/171

**Comment by ccll** [comment]
Unfortunately this is still a problem in my Kubernetes deployments, because there are many indirect layers of k8s network stack, so the exposed external URL is very different from the internal PROTOCOL://HOST:PORT.

1. protocol remapping: usually the k8s frontend load-balancer will do some SSL termination, and the pod(container) still serves as HTTP.
2. port remapping: k8s frontend load-balancer serves on 80/443 ports and forward traffics to the pod's internal port, and the k8s pod(container) usually serves on non-privileged ports (>1024) due to security concerns.
3. host remapping: a FQDN is pointing to k8s frontend load-balancer's IP address, and the load-balancer forwards traffic to correct pod(container), so in the browserless/chrome pod(container) we can't just bind `HOST` env var to the FQDN, usually `0.0.0.0` is used to bind to all interfaces inside the pod(container).

Due to those reasons, while in my k8s cluster I should have got a remote debugger URL like:
```
https://my-chrome.my-domain.com/devtools/inspector.html?wss=my-chrome.my-domain.com/devtools/page/xxxxxxxxxxxxx
```
but instead I got:
```
https://my-chrome.my-domain.com/devtools/inspector.html?ws=0.0.0.0:3000/devtools/page/xxxxxxxxxxxxx
```

I guess the correct way to handle this is to make a clear separation of the internal binding HOST/PORT binding from the external URL, for example:
1. Use env var `INTERNAL_HOST` to define internal bindings.
2. Use env var `EXTERNAL_URL` for emitting endpoints in the exposed remote debugger URL.

**Comment by ccll** [comment]
By reading through the code, I guess the problematic code is in this function:
https://github.com/browserless/chrome/blob/95d8c1d02abb76a89e2d78f7a238b5fb507a7c60/src/chrome-helper.ts#L206

Relavent lines:
https://github.com/browserless/chrome/blob/95d8c1d02abb76a89e2d78f7a238b5fb507a7c60/src/chrome-helper.ts#L210
https://github.com/browserless/chrome/blob/95d8c1d02abb76a89e2d78f7a238b5fb507a7c60/src/chrome-helper.ts#L230

In the meanwhile I've found another piece of code here, which correctly parses the `PROTOCOL/HOST/PORT` triple from the `window.location` property.
https://github.com/browserless/chrome/blob/95d8c1d02abb76a89e2d78f7a238b5fb507a7c60/debugger/index.html#L338
